# Python, numpy and pandas basics | Logistic regression casestudy using scikitlearn

### Basics of python

In [3]:
a = 15
b = 20
a < b

True

In [4]:
l = [1,2,3,4,5,6,10]
set(l)

{1, 2, 3, 4, 5, 6, 10}

Power

In [5]:
2**3

8

Slicing

In [6]:
l[1:2]

[2]

In [7]:
l[-1]

10

String Manipulation

In [8]:
s = "Hello"

In [9]:
s.upper()

'HELLO'

In [10]:
s

'Hello'

String are inmmutable

In [11]:
s.lower()

'hello'

Hence the functions don't change the value of the string

In [16]:
l.append("ten")
l

[1, 2, 3, 4, 5, 6, 10, 'ten', 'ten', 'ten']

In [17]:
l + ['10']

[1, 2, 3, 4, 5, 6, 10, 'ten', 'ten', 'ten', '10']

Create a matrix

In [18]:
l_1 = [1,2,3,4,5]
l_2 = [5,6,7,8,9]
l_3 = [1,3,5,7,9]
mat = [l_1,l_2,l_3]
mat

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9], [1, 3, 5, 7, 9]]

Taking input

In [19]:
inp = input("Give input")

Give inputHi


In [20]:
inp

'Hi'

User defined functions

In [24]:
def greeet(stri):
    print("Hello",stri)
    return;

In [25]:
greeet("Upgrad")

Hello Upgrad


In [27]:
a = 23000.2
b = 23000
if b > a:
    print("b is greateer than a")
elif a==b:
    print("a is equal to b")
else:
    print("a is greater than b")

a is greater than b


Try and except

In [28]:
astr = "123"
try:
    istr = int(astr)
except:
    print("astr is not convertible to integer")

In [29]:
istr

123

In [30]:
astr = "Hello upgrad"
try:
    istr = int(astr)
except:
    print("astr is not convertible to integer")

astr is not convertible to integer


####  while loop

In [31]:
i = 1
while i<10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9


In [41]:
friends = ['a','b','c','d','e']
len(friends)

5

In [48]:
for i in range(len(friends)-1,-1,-1):
    print(friends[i])

e
d
c
b
a


In [49]:
for i in range(0,len(friends)-1,2):
    print(friends[i])

a
c


# numpy 

In [50]:
import numpy as np

Convert a list to an array

In [51]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

range function in numpy

In [52]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Create an array of zeroes

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a matrix of ones

In [61]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Identity matrix

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Get a random uniform distribution

In [64]:
np.random.rand(5)

array([0.27768124, 0.50390052, 0.27539986, 0.62403092, 0.14701869])

Normal distribution

In [65]:
np.random.rand(3,3)

array([[0.54759684, 0.75276059, 0.40257572],
       [0.61221543, 0.62932206, 0.39624034],
       [0.49550148, 0.67798579, 0.23096317]])

Generate a random number within range

In [69]:
np.random.randint(1,100)

53

Generate n random integers between a range

In [70]:
np.random.randint(1,100,3)

array([66,  6, 48])

Convert an array into matrix

In [71]:
arr = np.arange(0,16,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Reshape the array to a 4X4 matrix

In [73]:
mat = arr.reshape(4,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Get the shape of the matrix

In [74]:
mat.shape

(4, 4)

arrays are mutable

In [75]:
arr[1] = 10
arr

array([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Slicing

In [77]:
arr[0:3]

array([ 0, 10,  2])

In [82]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Print all the numbers till the 5th index (5 exclusive)

In [83]:
arr[:5]

array([100, 100, 100, 100,   4])

Replace a range in the array with a number

In [80]:
arr[0:4] = 100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

Deepcopy vs shallowcopy

Shallow copy

In [92]:
a1 = np.arange(1,16)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
b1 = a1
b1[:] = 10
a1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

Deep copy

In [94]:
a2 = np.arange(1,16)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [96]:
b2 = a1.copy()
b2[:] = 100
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Accessing elements in an array

In [100]:
arr_2d = np.arange(0,16).reshape(4,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
arr_2d[2,2]

10

In [102]:
arr_2d[1]

array([4, 5, 6, 7])

Mathematical operations on arrays

In [103]:
a1 = np.arange(0,16).reshape(4,4)
a2 = np.arange(16,32).reshape(4,4)

In [113]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
a2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [104]:
a1 + a2

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [105]:
a1 * a2

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [106]:
np.sqrt(a1)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [107]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [108]:
np.max(a1)

15

In [109]:
np.min(a1)

0

Natural log (base e)

In [111]:
np.log(a1)
# log(0) is infinity. Runtime warning will be thrown. No error will be genrated

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [112]:
np.cos(a1)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

### Questions

Create an array of size 10; points should be linearly spaced

In [115]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Pandas

In [116]:
import pandas as pd

#### Series

In [125]:
labels = ['a','b','c','d']
labels

['a', 'b', 'c', 'd']

In [126]:
data = [10,30,50,70]
ar = np.array(data)
ar

array([10, 30, 50, 70])

Create a dictionary

In [127]:
d={'a':10,'b':30,'c':50,'d':70}
d

{'a': 10, 'b': 30, 'c': 50, 'd': 70}

Create a series with data and labels

In [128]:
pd.Series(data=data,index=labels)

a    10
b    30
c    50
d    70
dtype: int64

In [131]:
pd.Series(data,labels)

a    10
b    30
c    50
d    70
dtype: int64

In [133]:
series1 = pd.Series([1,2,3,4],['India','Afghanistan','China','Pakistan'])
series1

India          1
Afghanistan    2
China          3
Pakistan       4
dtype: int64

In [134]:
series2 = pd.Series([1,2,7,4],['India','Afghanistan','Bangladesh','Pakistan'])
series2

India          1
Afghanistan    2
Bangladesh     7
Pakistan       4
dtype: int64

Accessing an element

In [135]:
series1['India']

1

In [136]:
series3 = pd.Series(data=labels)
series3[0]

'a'

DataFrame - Pandas series object with an index

In [139]:
np.random.seed(1000)
df=pd.DataFrame(np.random.randn(5,3),['A','B','C','D','E'],['W','X','Y'])
df

W         X         Y
A -0.804458  0.320932 -0.025483
B  0.644324 -0.300797  0.389475
C -0.107437 -0.479983  0.595036
D -0.464668  0.667281 -0.806116
E -1.196070 -0.405960 -0.182377

Select rows

In [140]:
df['W']

A   -0.804458
B    0.644324
C   -0.107437
D   -0.464668
E   -1.196070
Name: W, dtype: float64

In [141]:
type(df['W'])

pandas.core.series.Series

In [142]:
df[['W','X']]

W         X
A -0.804458  0.320932
B  0.644324 -0.300797
C -0.107437 -0.479983
D -0.464668  0.667281
E -1.196070 -0.405960

Create a new column

In [143]:
df['new'] = df['W']+df['Y']

In [144]:
df

W         X         Y       new
A -0.804458  0.320932 -0.025483 -0.829941
B  0.644324 -0.300797  0.389475  1.033798
C -0.107437 -0.479983  0.595036  0.487598
D -0.464668  0.667281 -0.806116 -1.270783
E -1.196070 -0.405960 -0.182377 -1.378447

Drop the newly create column

In [145]:
df.drop('new',axis=1,inplace=True) # axis = 0 means the row and axis = 1 means column, inplace = True - for changes to occur
df

W         X         Y
A -0.804458  0.320932 -0.025483
B  0.644324 -0.300797  0.389475
C -0.107437 -0.479983  0.595036
D -0.464668  0.667281 -0.806116
E -1.196070 -0.405960 -0.182377

Drop a row

In [147]:
df.drop('E')

W         X         Y
A -0.804458  0.320932 -0.025483
B  0.644324 -0.300797  0.389475
C -0.107437 -0.479983  0.595036
D -0.464668  0.667281 -0.806116

In [148]:
df.shape 
# 5 denotes the number of rows and 3 denotes the number of columns

(5, 3)

Access rows

In [149]:
df.loc['A'] 

W   -0.804458
X    0.320932
Y   -0.025483
Name: A, dtype: float64

In [150]:
df.iloc[0]

W   -0.804458
X    0.320932
Y   -0.025483
Name: A, dtype: float64

In [151]:
df.loc['A','Y']

-0.025482880472072204

In [152]:
df.loc[['A','B'],['W','X']]

W         X
A -0.804458  0.320932
B  0.644324 -0.300797

Missing values

In [153]:
d = ({'A':[1,2,np.nan],'B':[6,np.nan,np.nan],'C':[1,4,5]})

df = pd.DataFrame(d)

df


A    B  C
0  1.0  6.0  1
1  2.0  NaN  4
2  NaN  NaN  5

Replacing with median

Drop rows with NA values

In [154]:
df.dropna() # For Rows

A    B  C
0  1.0  6.0  1

Drop columns with NA values

In [155]:
df.dropna(axis=1) # For Columns

C
0  1
1  4
2  5

Remove those columns which has atleast 2 missing values

In [157]:
df.dropna(thresh=2)

A    B  C
0  1.0  6.0  1
1  2.0  NaN  4

Imputing missing values with mean
imputing the missing values in column 'A' with it's mean

In [159]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

##### Groupby function

In [160]:
data = {'Company':['Goog','MSFT','ABINB','DMART','TCS','TCS'],
        'Person':['Ra','Ma','Ta','Ka','Ga','Fa'],
        'Sales': [200,1000,100001,232,445,567]}

df = pd.DataFrame(data)
df

Company Person   Sales
0    Goog     Ra     200
1    MSFT     Ma    1000
2   ABINB     Ta  100001
3   DMART     Ka     232
4     TCS     Ga     445
5     TCS     Fa     567

groupby is the function to group values in pandas

In [ ]:
grouping by the 'company' column

In [162]:
r=df.groupby('Company')

In [163]:
r.mean()

Sales
Company        
ABINB    100001
DMART       232
Goog        200
MSFT       1000
TCS         506

In [164]:
r.sum()

Sales
Company        
ABINB    100001
DMART       232
Goog        200
MSFT       1000
TCS        1012

In [165]:
r.count()

Person  Sales
Company               
ABINB         1      1
DMART         1      1
Goog          1      1
MSFT          1      1
TCS           2      2

Oneliner for the above operation

In [166]:
df.groupby("Company").count()

Person  Sales
Company               
ABINB         1      1
DMART         1      1
Goog          1      1
MSFT          1      1
TCS           2      2

In [167]:
df.groupby('Company').max()

Person   Sales
Company               
ABINB       Ta  100001
DMART       Ka     232
Goog        Ra     200
MSFT        Ma    1000
TCS         Ga     567

In [168]:
df.groupby('Company').describe()

Sales                                                               \
        count      mean        std       min       25%       50%       75%   
Company                                                                      
ABINB     1.0  100001.0        NaN  100001.0  100001.0  100001.0  100001.0   
DMART     1.0     232.0        NaN     232.0     232.0     232.0     232.0   
Goog      1.0     200.0        NaN     200.0     200.0     200.0     200.0   
MSFT      1.0    1000.0        NaN    1000.0    1000.0    1000.0    1000.0   
TCS       2.0     506.0  86.267027     445.0     475.5     506.0     536.5   

                   
              max  
Company            
ABINB    100001.0  
DMART       232.0  
Goog        200.0  
MSFT       1000.0  
TCS         567.0

Merging and concatinating

In [169]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [170]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [171]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [172]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

concatenate all the rows from all the data frames
Similar to Rbind in R 

In [174]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

Concatenate dataframes column wise <br>
similar to cbind in R

In [178]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

Merge

In [179]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [180]:
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [181]:
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [182]:
pd.merge(left,right,how='inner',on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [184]:
pd.merge(left, right, how='outer', on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

Read input from the CSV file

In [185]:
training = pd.read_csv("data/train.csv")

In [186]:
training

id  A      B       C    D    E    F    G      H  I  J   K  L  M      N  \
0      1  b  18.42  10.415    y    p   aa    v  0.125  t  f   0  f  g  120.0   
1      2  a  21.75  11.750    u    g    c    v  0.250  f  f   0  t  g  180.0   
2      3  b  30.17   1.085    y    p    c    v  0.040  f  f   0  f  g  170.0   
3      4  b  22.67   2.540    y    p    c    h  2.585  t  f   0  f  g    0.0   
4      5  a  36.00   1.000    u    g    c    v  2.000  t  t  11  f  g    0.0   
5      6  b  31.25   1.125    u    g   ff   ff  0.000  f  t   1  f  g   96.0   
6      7  b  18.58   5.710    u    g    d    v  0.540  f  f   0  f  g  120.0   
7      8  b  32.42   3.000    u    g    d    v  0.165  f  f   0  t  g  120.0   
8      9  b  37.33   6.500    u    g    m    h  4.250  t  t  12  t  g   93.0   
9     10  b  35.00   3.375    u    g    c    h  8.290  f  f   0  t  g    0.0   
10    11  a  19.17   0.585    y    p   aa    v  0.585  t  f   0  t  g  160.0   
11    12  b  42.75   4.085    u    g   aa    v  0.040  f  f   0  f  g  108.0   
12    13  a  21.67  11.500    y    p    j    j  0.000  t  t  11  t  g    0.0   
13    14  b  31.83   0.040    y    p    m    v  0.040  f  f   0  f  g    0.0   
14    15  b  29.42   1.250    u    g    c    h  0.250  f  t   2  t  g  400.0   
15    16  a  28.58   3.750    u    g    c    v  0.250  f  t   1  t  g   40.0   
16    17  b  21.33   7.500    u    g   aa    v  1.415  t  t   1  f  g   80.0   
17    18  b  34.50   4.040    y    p    i   bb  8.500  t  t   7  t  g  195.0   
18    19  b  16.92   0.335    y    p    k    v  0.290  f  f   0  f  s  200.0   
19    20  a  17.33   9.500    u    g   aa    v  1.750  f  t  10  t  g    0.0   
20    21  a  30.50   6.500    u    g    c   bb  4.000  t  t   7  t  g    0.0   
21    22  b  33.58   0.250    u    g    i   bb  4.000  f  f   0  t  s  420.0   
22    23  a  49.00   1.500    u    g    j    j  0.000  t  f   0  t  g  100.0   
23    24  b  34.00   5.500    y    p    c    v  1.500  f  f   0  t  g   60.0   
24    25  b  21.58   0.790    y    p   cc    v  0.665  f  f   0  f  g  160.0   
25    26  b  16.08   0.750    u    g    c    v  1.750  t  t   5  t  g  352.0   
26    27  b  38.17  10.125    u    g    x    v  2.500  t  t   6  f  g  520.0   
27    28  b  36.17   0.420    y    p    w    v  0.290  f  f   0  t  g  309.0   
28    29  a  17.58   9.000    u    g   aa    v  1.375  t  f   0  t  g    0.0   
29    30  b  30.83   0.000    u    g    w    v  1.250  t  t   1  f  g  202.0   
..   ... ..    ...     ...  ...  ...  ...  ...    ... .. ..  .. .. ..    ...   
522  523  a  28.42   3.500    u    g    w    v  0.835  t  f   0  f  s  280.0   
523  524  a  17.92  10.210    u    g   ff   ff  0.000  f  f   0  f  g    0.0   
524  525  b  31.08   3.085    u    g    c    v  2.500  f  t   2  t  g  160.0   
525  526  b  39.58  13.915    u    g    w    v  8.625  t  t   6  t  g   70.0   
526  527  a  33.25   2.500    y    p    c    v  2.500  f  f   0  t  g    0.0   
527  528  b  18.17  10.250    u    g    c    h  1.085  f  f   0  f  g  320.0   
528  529  a  25.00  11.000    y    p   aa    v  4.500  t  f   0  f  g  120.0   
529  530  b  22.83   3.000    u    g    m    v  1.290  t  t   1  f  g  260.0   
530  531  b  36.25   5.000    u    g    c   bb  2.500  t  t   6  f  g    0.0   
531  532  a  38.25   6.000    u    g    k    v  1.000  t  f   0  t  g    0.0   
532  533  b  23.08   2.500    u    g   ff   ff  0.085  f  f   0  t  g  100.0   
533  534  b  25.00  11.250    u    g    c    v  2.500  t  t  17  f  g  200.0   
534  535  b  22.58  10.040    u    g    x    v  0.040  t  t   9  f  g   60.0   
535  536  a  22.83   2.290    u    g    q    h  2.290  t  t   7  t  g  140.0   
536  537  a  58.33  10.000    u    g    q    v  4.000  t  t  14  f  g    0.0   
537  538  b  39.83   0.500    u    g    m    v  0.250  t  f   0  f  s  288.0   
538  539  b  23.17   0.000  NaN  NaN  NaN  NaN  0.000  f  f   0  f  p    NaN   
539  540  b  42.00   0.205    u    g    i    h  5.125  t  f   0  f  g  400.0   
540  5

In [189]:
training.describe()

id           B           C           H           K  \
count  552.000000  543.000000  552.000000  552.000000  552.000000   
mean   276.500000   31.364899    4.780136    2.259176    2.318841   
std    159.492947   11.873665    4.938454    3.442564    4.297867   
min      1.000000   13.750000    0.000000    0.000000    0.000000   
25%    138.750000   22.500000    1.000000    0.165000    0.000000   
50%    276.500000   28.170000    2.750000    1.000000    0.000000   
75%    414.250000   37.665000    7.561250    2.750000    3.000000   
max    552.000000   80.250000   28.000000   28.500000   40.000000   

                 N              O           P  
count   541.000000     552.000000  552.000000  
mean    175.162662    1087.576087    0.552536  
std     154.873746    5758.841945    0.497683  
min       0.000000       0.000000    0.000000  
25%      60.000000       0.000000    0.000000  
50%     152.000000       3.500000    1.000000  
75%     268.000000     364.750000    1.000000  
max    1160.000000  100000.000000    1.000000

### Logistic regression

In [190]:
from sklearn.linear_model import LogisticRegression

In [191]:
Xtrain= training.iloc[:,1:16]

Ytrain = training.iloc[:,16]

In [192]:
Xtrain.describe()

B           C           H           K            N  \
count  543.000000  552.000000  552.000000  552.000000   541.000000   
mean    31.364899    4.780136    2.259176    2.318841   175.162662   
std     11.873665    4.938454    3.442564    4.297867   154.873746   
min     13.750000    0.000000    0.000000    0.000000     0.000000   
25%     22.500000    1.000000    0.165000    0.000000    60.000000   
50%     28.170000    2.750000    1.000000    0.000000   152.000000   
75%     37.665000    7.561250    2.750000    3.000000   268.000000   
max     80.250000   28.000000   28.500000   40.000000  1160.000000   

                   O  
count     552.000000  
mean     1087.576087  
std      5758.841945  
min         0.000000  
25%         0.000000  
50%         3.500000  
75%       364.750000  
max    100000.000000

In [193]:
Xtrain

A      B       C    D    E    F    G      H  I  J   K  L  M      N     O
0    b  18.42  10.415    y    p   aa    v  0.125  t  f   0  f  g  120.0   375
1    a  21.75  11.750    u    g    c    v  0.250  f  f   0  t  g  180.0     0
2    b  30.17   1.085    y    p    c    v  0.040  f  f   0  f  g  170.0   179
3    b  22.67   2.540    y    p    c    h  2.585  t  f   0  f  g    0.0     0
4    a  36.00   1.000    u    g    c    v  2.000  t  t  11  f  g    0.0   456
5    b  31.25   1.125    u    g   ff   ff  0.000  f  t   1  f  g   96.0    19
6    b  18.58   5.710    u    g    d    v  0.540  f  f   0  f  g  120.0     0
7    b  32.42   3.000    u    g    d    v  0.165  f  f   0  t  g  120.0     0
8    b  37.33   6.500    u    g    m    h  4.250  t  t  12  t  g   93.0     0
9    b  35.00   3.375    u    g    c    h  8.290  f  f   0  t  g    0.0     0
10   a  19.17   0.585    y    p   aa    v  0.585  t  f   0  t  g  160.0     0
11   b  42.75   4.085    u    g   aa    v  0.040  f  f   0  f  g  108.0   100
12   a  21.67  11.500    y    p    j    j  0.000  t  t  11  t  g    0.0     0
13   b  31.83   0.040    y    p    m    v  0.040  f  f   0  f  g    0.0     0
14   b  29.42   1.250    u    g    c    h  0.250  f  t   2  t  g  400.0   108
15   a  28.58   3.750    u    g    c    v  0.250  f  t   1  t  g   40.0   154
16   b  21.33   7.500    u    g   aa    v  1.415  t  t   1  f  g   80.0  9800
17   b  34.50   4.040    y    p    i   bb  8.500  t  t   7  t  g  195.0     0
18   b  16.92   0.335    y    p    k    v  0.290  f  f   0  f  s  200.0     0
19   a  17.33   9.500    u    g   aa    v  1.750  f  t  10  t  g    0.0    10
20   a  30.50   6.500    u    g    c   bb  4.000  t  t   7  t  g    0.0  3065
21   b  33.58   0.250    u    g    i   bb  4.000  f  f   0  t  s  420.0     0
22   a  49.00   1.500    u    g    j    j  0.000  t  f   0  t  g  100.0    27
23   b  34.00   5.500    y    p    c    v  1.500  f  f   0  t  g   60.0     0
24   b  21.58   0.790    y    p   cc    v  0.665  f  f   0  f  g  160.0     0
25   b  16.08   0.750    u    g    c    v  1.750  t  t   5  t  g  352.0   690
26   b  38.17  10.125    u    g    x    v  2.500  t  t   6  f  g  520.0   196
27   b  36.17   0.420    y    p    w    v  0.290  f  f   0  t  g  309.0     2
28   a  17.58   9.000    u    g   aa    v  1.375  t  f   0  t  g    0.0     0
29   b  30.83   0.000    u    g    w    v  1.250  t  t   1  f  g  202.0     0
..  ..    ...     ...  ...  ...  ...  ...    ... .. ..  .. .. ..    ...   ...
522  a  28.42   3.500    u    g    w    v  0.835  t  f   0  f  s  280.0     0
523  a  17.92  10.210    u    g   ff   ff  0.000  f  f   0  f  g    0.0    50
524  b  31.08   3.085    u    g    c    v  2.500  f  t   2  t  g  160.0    41
525  b  39.58  13.915    u    g    w    v  8.625  t  t   6  t  g   70.0     0
526  a  33.25   2.500    y    p    c    v  2.500  f  f   0  t  g    0.0     2
527  b  18.17  10.250    u    g    c    h  1.085  f  f   0  f  g  320.0    13
528  a  25.00  11.000    y    p   aa    v  4.500  t  f   0  f  g  120.0     0
529  b  22.83   3.000    u    g    m    v  1.290  t  t   1  f  g  260.0   800
530  b  36.25   5.000    u    g    c   bb  2.500  t  t   6  f  g    0.0   367
531  a  38.25   6.000    u    g    k    v  1.000  t  f   0  t  g    0.0     0
532  b  23.08   2.500    u    g   ff   ff  0.085  f  f   0  t  g  100.0  4208
533  b  25.00  11.250    u    g    c    v  2.500  t  t  17  f  g  200.0  1208
534  b  22.58  10.040    u    g    x    v  0.040  t  t   9  f  g   60.0   396
535  a  22.83   2.290    u    g    q    h  2.290  t  t   7  t  g  140.0  2384
536  a  58.33  10.000    u    g    q    v  4.000  t  t  14  f  g    0.0  1602
537  b  39.83   0.500    u    g    m    v  0.250  t  f   0  f  s  288.0     0
538  b  23.17   0.000  NaN  NaN  NaN  NaN  0.000  f  f   0  f  p    NaN     0
539  b  42.00   0.205    u    g    i    h  5.125  t  f   0  f  g  400.0     0
540  b  27.25   0.625    u    g   aa    v  0.455  t  f   0  t  g  200.0     0
541  b  23.08  11.500    u 

In [194]:
Xtrain.isnull().sum()

A     8
B     9
C     0
D     5
E     5
F     7
G     7
H     0
I     0
J     0
K     0
L     0
M     0
N    11
O     0
dtype: int64

In [195]:
Xtrain.isnull().any().any()

True

In [196]:
Ytrain.isnull().any().any()

False

In [197]:
Xtrain.B.describe()

count    543.000000
mean      31.364899
std       11.873665
min       13.750000
25%       22.500000
50%       28.170000
75%       37.665000
max       80.250000
Name: B, dtype: float64

In [198]:
Xtrain.G.describe()

count     545
unique      9
top         v
freq      319
Name: G, dtype: object

Missing value imputation <br>
'A', 'D', 'E', 'F', 'G' are categorical values

In [200]:
# Replacing with mode for categorical values
for column in ['A', 'D', 'E', 'F', 'G']:
    Xtrain[column].fillna(Xtrain[column].mode()[0], inplace=True)

For numeric values, we would replace the missing values with median
Instead of replacing the missing values directly with median, we are grouping the continuous values by the target variable(column "P") and then calculating the median and replace the NA values with median for the respective categories

In [201]:
Xtrain1= Xtrain[['B','N']] 

Xtrain1 = pd.concat([Xtrain1,Ytrain],axis=1)

Xtrain1=Xtrain1.groupby('P', group_keys=False).apply(lambda x: x.fillna(x.median()).astype(float))    


Removing the actual columns and replacing the newly created columns in the actual data

In [202]:
Xtrain = Xtrain.drop(['B','N'],axis=1)

Xtrain1= Xtrain1.drop('P',axis=1)

Xtrain = pd.concat([Xtrain,Xtrain1],axis=1)


In [203]:
Xtrain.isnull().sum()

A    0
C    0
D    0
E    0
F    0
G    0
H    0
I    0
J    0
K    0
L    0
M    0
O    0
B    0
N    0
dtype: int64

Onehot encoding for the categorical values ( Creating dummy variables)

In [204]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1 = LabelEncoder()
Xtrain.iloc[:,0] = labelencoder_X_1.fit_transform(Xtrain.iloc[:,0]) 
labelencoder_X_2 = LabelEncoder()
Xtrain.iloc[:,2] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,2])
labelencoder_X_3 = LabelEncoder()
Xtrain.iloc[:,3] = labelencoder_X_3.fit_transform(Xtrain.iloc[:,3])
labelencoder_X_4 = LabelEncoder()
Xtrain.iloc[:,4] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,4])
labelencoder_X_5 = LabelEncoder()
Xtrain.iloc[:,5] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,5])

labelencoder_X_7 = LabelEncoder()
Xtrain.iloc[:,7] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,7])

labelencoder_X_8 = LabelEncoder()
Xtrain.iloc[:,8] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,8])


labelencoder_X_10 = LabelEncoder()
Xtrain.iloc[:,10] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,10])


labelencoder_X_11 = LabelEncoder()
Xtrain.iloc[:,11] = labelencoder_X_2.fit_transform(Xtrain.iloc[:,11])


Creating new variables based on the frequency

In [205]:
Xtrain['A_freq'] = Xtrain.groupby('A')['A'].transform('count')

Xtrain['D_freq'] = Xtrain.groupby('D')['D'].transform('count')

Xtrain['E_freq'] = Xtrain.groupby('E')['E'].transform('count')

Xtrain['F_freq'] = Xtrain.groupby('F')['F'].transform('count')

Xtrain['G_freq'] = Xtrain.groupby('G')['G'].transform('count')

Xtrain['I_freq'] = Xtrain.groupby('I')['I'].transform('count')

Xtrain['J_freq'] = Xtrain.groupby('J')['J'].transform('count')

Xtrain['K_freq'] = Xtrain.groupby('K')['K'].transform('count')

Xtrain['L_freq'] = Xtrain.groupby('L')['L'].transform('count')

Xtrain['M_freq'] = Xtrain.groupby('M')['M'].transform('count')


Fitting a logistic regression model

In [206]:
logmodel = LogisticRegression()
logmodel.fit(Xtrain,Ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)